development:
  password: ${repupi_dawn_DEV_PASSWD}
  theme_id: ${repupi_dawn_DEV_THEMEID}
  store: ${repupi_dawn_DEV_SHOP}
  
# Windows %APPDATA%\Shopify\Themekit\variables
# Linux/BSDs ${XDG_CONFIG_HOME}/Shopify/Themekit/variables
# MacOSX ${HOME}/Library/Application Support/Shopify/Themekit/variables
# any --vars flag provides a path to a file for loading variables
# file to load ignore patterns, check out the ignore file example